# Change these first
owner: seanstaffiery # Your GitHub organization or username, where this repository lives
repo: status.seanstaffiery.com # The name of this repository

sites:
  - name: Central Website - seanstaffiery.com
    url: https://seanstaffiery.com
  - name: File Server - files.seanstaffiery.com
    url: https://files.seanstaffiery.com
  - name: Flarum Forum - forum.seanstaffiery.com
    url: https://forum.seanstaffiery.com
  - name: Projects Website - projects.seanstaffiery.com
    url: https://projects.seanstaffiery.com
  - name: PGP Fingerprints - pgp.seanstaffiery.com
    url: https://pgp.seanstaffiery.com
  - name: NextCloud - home.seanstaffiery.com
    url: https://home.seanstaffiery.com
  - name: Development Blog - blog.seanstaffiery.com
    url: https://blog.seanstaffiery.com
  - name: Resume Website - seanstaffiery.dev
    url: https://seanstaffiery.dev
  - name: Repository - seanstaffiery.net
    url: https://seanstaffiery.net  
  - name: Family Website - thehosmers.com
    url: https://thehosmers.com
  - name: IPFS Central Site - ipfs.io
    url: https://ipfs.io
  - name: IPFS Gateway 1/2
    url: https://ipfs.seanstaffiery.com
  - name: IPFS Gateway 2/2
    url: https://ipfs.seanstaffiery.dev
  - name: DigitalOcean
    url: https://digitalocean.com
  - name: Cloudflare
    url: https://www.cloudflare.com
  - name: Zoho
    url: https://zoho.com
  - name: Proofpoint
    url: https://proofpoint.com
  - name: Microsoft Azure (Azure) 
    url: https://azure.com
  - name: Google Cloud Platform (GCP)
    url: https://cloud.google.com
  - name: Amazon Web Services (AWS)
    url: https://aws.amazon.com
  - name: Firebase
    url: https://firebase.google.com
  - name: GitHub
    url: https://github.com
  - name: SendGrid
    url: https://sendgrid.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.seanstaffiery.com
  # baseUrl: /your-repo-name
  theme: dark
  logoUrl: https://seanstaffiery.com/favicon.ico
  name: status.seanstaffiery.com
  introTitle: "Sean Staffiery Holdings Status Page"
  introMessage: This webpage hosts the status of all systems and services that Sean Staffiery Holdings uses.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
