# Change these first
owner: seanstaffiery # Your GitHub organization or username, where this repository lives
repo: status.seanstaffiery.com # The name of this repository

sites:
  - name: seanstaffiery.com
    url: https://seanstaffiery.com
  - name: seanstaffiery.dev
    url: https://seanstaffiery.dev
  - name: thehosmers.com
    url: https://thehosmers.com
  - name: projects.seanstaffiery.com
    url: https://projects.seanstaffiery.com
  - name: pgp.seanstaffiery.com
    url: https://pgp.seanstaffiery.com
  - name: DigitalOcean
    url: https://status.digitalocean.com
  - name: Cloudflare
    url: https://www.cloudflarestatus.com
  - name: Zoho
    url: https://status.zoho.com
  - name: Microsoft Azure
    url: https://status.azure.com/en-us/status
  - name: Google Cloud
    url: https://status.cloud.google.com
  - name: Amazon Web Services
    url: https://status.aws.amazon.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.seanstaffiery.com
  # baseUrl: /your-repo-name
  theme: dark
  logoUrl: https://seanstaffiery.com/favicon.ico
  name: status.seanstaffiery.com
  introTitle: "Sean Staffiery Holdings Status Page"
  introMessage: This webpage hosts the status of all systems and services that Sean Staffiery Holdings uses
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
